import AboutIcon from './icons/about.svg';
import EditIcon from './icons/edit.svg';
import PostIcon from './icons/post.svg';
import RulerIcon from './icons/ruler.svg';
import TagIcon from './icons/tag.svg';
import ErrorIcon from './icons/error.svg';
import PhotoIcon from './icons/photo.svg';
import GridIcon from './icons/grid.svg';
import MailIcon from './icons/mail.svg';
import LogoIcon from './icons/logo.svg';
import GithubIcon from './icons/github.svg';
import Unknown from './icons/unknown.svg';
import YuQueIcon from './icons/yuque.svg';
import MicroscopeSlide from './icons/microscope_slide .svg';

export { AboutIcon }
export { EditIcon }
export { PostIcon }
export { RulerIcon }
export { TagIcon }
export { ErrorIcon }
export { PhotoIcon }
export { GridIcon }
export { MailIcon }
export { LogoIcon }
export { GithubIcon }
export { Unknown }
export { YuQueIcon }
export { MicroscopeSlide }
