import AboutIcon from './icons/about.svg';
import EditIcon from './icons/edit.svg';
import PostIcon from './icons/post.svg';
import RulerIcon from './icons/ruler.svg';
import TagIcon from './icons/tag.svg';
import ErrorIcon from './icons/error.svg';
import PhotoIcon from './icons/photo.svg';
import GridIcon from './icons/grid.svg';
import MailIcon from './icons/mail.svg';
import LogoIcon from './icons/logo.svg';
import GithubIcon from './icons/github.svg';
import Unknown from './icons/unknown.svg';
import YuQueIcon from './icons/yuque.svg';
import MicroscopeSlide from './icons/microscope_slide .svg';
import BoxIcon from './icons/box.svg';
import HelpIcon from './icons/help.svg'
import TextIcon from './icons/text.svg';
import FigmaIcon from './icons/figma.svg';
import NpmIcon from './icons/npm.svg';
import InvalidIcon from './icons/invalid.svg';

export { InvalidIcon }
export { NpmIcon }
export { FigmaIcon }
export { BoxIcon }
export { HelpIcon }
export { TextIcon }
export { AboutIcon }
export { EditIcon }
export { PostIcon }
export { RulerIcon }
export { TagIcon }
export { ErrorIcon }
export { PhotoIcon }
export { GridIcon }
export { MailIcon }
export { LogoIcon }
export { GithubIcon }
export { Unknown }
export { YuQueIcon }
export { MicroscopeSlide }
